### PR TITLE
Dispose disposables before discarding them.

### LINKED ISSUE #87: Not disposing of disposables on dev reload
Would love to know how to run a test on my claim. Looks to me like [extension.cljs#L18](https://github.com/BetterThanTomorrow/joyride/blob/b6c672b04f1f9af8a2280bcc379353e9557a25fd/src/joyride/extension.cljs#L18) fails to dispose of disposables when deactivating.

```clojure
(defn- clear-disposables! []
   ;; First we reset disposables to empty vec.
  (swap! db/!app-db assoc :disposables [])
   ;; Then we try to call .dispose on each disposable.
   ;;  But since the vec is empty, this is a no-op.
  (p/run! (fn [^js disposable]
            (.dispose disposable))
          (:disposables @db/!app-db)))
```

edit: I guess it's not really that hard to test: Just pretend not in VS Code and store some disposables with spy `.dispose` functions. Still would be nice to know a reasonable way to verify what VS Code is doing here.

### PR DESCRIPTION
**Pull request by skylize**
On dev reload, correctly call `dispose` method of each disposable
before resetting the vector of stored disposables. Fixes #87

### CODE REVIEW

File: src/joyride/extension.cljs [hunk 1]
```diff
@@ -16,10 +16,10 @@
     (.push (.-subscriptions context) disposable)))
 
 (defn- clear-disposables! []
-  (swap! db/!app-db assoc :disposables [])
-  (p/run! (fn [^js disposable]
+  (run! (fn [^js disposable]
```
Comment (PEZ) [inline src/joyride/extension.cljs:19]: Might we risk starting to add disposable before we've cleared the old ones if we don't wait for the promises to resolve? It won't probably matter in practice, but there's a small risk of two instances of the same subscription being active at the same time, isn't it?

**Review by PEZ — APPROVED** [review]
LGTM. I'll leave it up to you about the clear promises. 😄  

Please add a changelog entry linking to the issue being fixed. Then we're good to go.

File: src/joyride/extension.cljs (hunk 1 above)
Comment (skylize) [reply src/joyride/extension.cljs:19]: The API docs repeatedly warn "Note that an asynchronous function is not awaited." when talking about disposables.

The (obvious, yet surprising) translation is that calling `dispose` on an instance of `Disposable` does not return a promise, even if the underlying dispose function does. Not sure about the mechanics or reason, but this is pretty simple to demonstrate in the repl.

```clojure
cljs꞉joyride.extension꞉>
(let [disposable (vscode/Disposable.
                    (fn []
                      (println "disposing")
                       ;; underlying disposal function returns a promise
                      (p/delay 1 "disposed")))]
    (.dispose disposable))

 ;; The promise-returning function is called
disposing
 ;; but `.dispose` immediately returns nil instead of the promise.
nil 
 ;; The result of the promise, and any chance to wait for resolution is lost.
```
Wrapping the disposal process in `p/run!` here simply wraps a bunch of nils in a promise, rather than actually awaiting any existing promises. We get a false impression of safety. If a race somehow does exist, there really is nothing we can do now.

Shouldn't be a problem though because separate instances are just that, "separate instances". JavaScript does not have meaningful equality semantics. Outside of the weird type coercion, JS generally relies on strict referential equality.
```javascript
const o = {a: 1}
o === o            // ==> true
o === {a: 1}       // ==> false
```
So the only way to get race conditions here is from strict sharing of underlying resources. Presumably by this point in time (having chosen to implement such a no-wait disposal process) Microsoft will have worked out any possible race conditions from Disposables they issue? 🤞

The only time we should need to worry about races is if we generate our own disposables, and connect to existing resources, but then terminate those resources in `dispose` as if we own them. (Which, of course, we should generally avoid.) For example:
```clojure
(let [repl (if (running-repl?)
              ;; try to reuse existing repl
             (connect-to-repl)
              ;; else create our own
             (start-and-connect-to-repl))
      disposable #js{dispose 
                      ;; blindly kill the repl, even if another party created it
                     (fn [kill repl])}]
  .push (.-subscriptions context) disposable)
```

Comment (PEZ) [reply src/joyride/extension.cljs:19]: Thanks for clarifying this! 🙏

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,7 @@
 Changes to Joyride
 
 ## [Unreleased]
+- Fix: [Not disposing of disposables on dev reload](https://github.com/BetterThanTomorrow/joyride/issues/87)
```
Comment (PEZ) [inline CHANGELOG.md:6]:
```suggestion

- Fix: [Not disposing of disposables on dev reload](https://github.com/BetterThanTomorrow/joyride/issues/87)
```

I think the release script might be sensitive to the blank line missing. (I should know. since I wrote the script, but anyway.)
