### PR TITLE
52 get started content

### LINKED ISSUE #46: Don't unconditionally show the Joyride output channel on start
Device some way to opt out of the Joyride message/output channel showing at startup.

### LINKED ISSUE #51: Joyride throws an error when activated in a window with no folder
When joyride is activated in a VSCode window with no folders added to the workspace, it throws this error:

```
[2022-05-10 15:50:53.966] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at <path/to>/joyride/out/js/cljs-runtime/joyride/life_cycle.cljs:16:37
    at <path/to>/joyride/out/joyride.js:70:44
    at <path/to>/joyride/out/joyride.js:1593:1
    at <path/to>/repos/joyride/out/joyride.js:5:26
    at Object.<anonymous> (/Users/maxrothman/repos/joyride/out/joyride.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at node:internal/modules/cjs/loader:876:12
    at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13343)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
    at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61719)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/maxrothman/repos/joyride/extension.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at node:internal/modules/cjs/loader:876:12
    at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13343)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
    at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61719)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at m._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:30353)
    at m._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:14751)
    at m._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:13702)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
    at _waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
    at _initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)
```

Digging around a little more, it appears that `vscode/workspace.rootPath` is undefined [in life_cycle.cljs](https://github.com/maxrothman/joyride/blob/148d2afd9ed4e2250ef8eb05e93fc86b31ca6f39/src/main/joyride/life_cycle.cljs#L16).

Discussed in: https://clojurians.slack.com/archives/C03DPCLCV9N/p1652212180463169

### LINKED ISSUE #52: Create example user scripts if they are not present
As a user who has just installed Joyride, it's boring with no content at all. Joyride could create two example scripts so that the new user has something to start playing around with:

- `hello_joyride.cljs` - with some basic VS Code API used, possibly just showing an information message with two buttons, one which takes you to the Joyride examples page.
- `activate.cljs` - which could just show the Joyride output channel and say something in it. Maybe print the paths to the two created files.

### PR DESCRIPTION
**Pull request by PEZ**
* Add Getting Started User scripts. Fixes #52
* Stop showing the Joyride channel on start. Fixes #46
* Make User scripts work if there is no workspace folder open. Fixes #51

The user scripts created are:

* activate.cljs
* hello_joyride_user_script.cljs

These are installed if not present. The activate script opens the Joyride channel and informs about that it does this. It is now up to the user to update the activate script to keep or get rid of the behaviour.

### CODE REVIEW

File: assets/getting-started-content/activate.cljs [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+  ;; New to Calva and/or Clojure? Use the Calva command:
+  ;;   *Fire up the Getting Started REPL*
+  ;; It will guide you through the basics.
+
+  (-> 4
+      (* 10)
+      (+ 1)
+      inc)
+
+  (-> (vscode/window.showInformationMessage "Be a Joyrider 🎸" "Yes" "Of course!")
```
Comment (borkdude) [inline assets/getting-started-content/activate.cljs:25]: Probably `(p/do ..)` makes more sense here?

File: package.json [hunk 2]
```diff
@@ -43,6 +43,7 @@
     }
   ],
   "activationEvents": [
+    "*",
```
Comment (borkdude) [inline package.json:46]: if you add `*` are others still needed? why is this necessary?

Comment (PEZ) [reply package.json:46]: The others are not strictly necessary. I kept them so that when we figure out how to not use `"*"` here we can just remove it.

The reason is that if Joyride started later in the process, its output panel would show regardless of us showing it or not. As a result of creating it. I don't know why this happens. Some strange decision at MS, or if it is a bug.

File: package.json [hunk 3]
```diff
@@ -112,9 +113,11 @@
     "prewatch": "npm run clean",
     "compile": "npx shadow-cljs compile :extension",
     "release": "npx shadow-cljs release :extension",
+    "package": "npx vsce package --allow-star-activation",
     "vscode:prepublish": "npm run clean && npm run release"
   },
   "dependencies": {
+    "fast-glob": "^3.2.11",
```
[the remark this answers is not in the document]
Comment (PEZ) [reply package.json:120]: Glob-ing is tricky stuff. I don't know how to roll our own. If we can add some Clojure lib that does it, we can remove this one.

Also: Calva utilises the npm ecosystem a lot. Never brings us trouble beyond making npm audit happy. So I guess we have different experiences with JS deps. 😄

[the remark this answers is not in the document]
Comment (PEZ) [reply package.json:120]: It's a pity that the vscode globber stops working when there is no root folder. Seems that it is for no reason, because when there is one, it can glob the User scripts just fine.

[the remark this answers is not in the document]
Comment (borkdude) [reply package.json:120]: Oh right, the vscode globber is what I thought was built-in.

File: assets/getting-started-content/activate.cljs (hunk 1 above)
Comment (borkdude) [reply assets/getting-started-content/activate.cljs:25]:
```
(p/do (some-promise) (some-other-promise) (some-non-promise))
``

is the same as the above.

**Comment by PEZ** [comment]
I tried. 😄 Started out with the user content, and then that needed the user script issue to be fixed.

**Comment by borkdude** [comment]
This is probably because you added it to `:keep-as-require` which doesn't bundle the library. Did you see my message about the other lighter-weight lib?

**Comment by borkdude** [comment]
No it won't, same issue. With keep-as-require you're telling shadow to not compile in the library.

**Comment by borkdude** [comment]
Why would it magically not need that? What was the cause of not working?

**Comment by borkdude** [comment]
Or maybe that's a configuration in the typescript stuff?

**Comment by PEZ** [comment]
We use webpack there... Maybe that is what we need to do here as well.

**Comment by PEZ** [comment]
Ready for review again, @borkdude 🙏

File: assets/getting-started-content/activate.cljs [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+  ;; New to Calva and/or Clojure? Use the Calva command:
+  ;;   *Fire up the Getting Started REPL*
+  ;; It will guide you through the basics.
+
+  (-> 4
+      (* 10)
+      (+ 1)
+      inc)
+
+  (p/-> (vscode/window.showInformationMessage "Be a Joyrider 🎸" "Yes" "Of course!")
```
Comment (borkdude) [inline assets/getting-started-content/activate.cljs:28]: Ah, now I get it you want to use the return value from showInfoMsg.

Why not use p/let?

```
(p/let [choice (vscode/... ...)]
  (if choice ...))
```

**Comment by PEZ** [comment]
Thanks for the p/let suggestions, @borkdude. Much cleaner. Maybe you should scrutinize some of my other example scripts as well. I have still to get used to promesa sweetness.

**Comment by borkdude** [comment]
@PEZ Thanks, LGTM!

File: assets/getting-started-content/activate.cljs [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+;; place for you to initialize things. E.g. install event handlers,
+;; print motivational messages, or whatever.
+
+;; You can run this and other User scripts with the command:
+;;   *Joyride: Run User Script*
+
+(comment
+  ;; Use Calva to start the Joyride REPL and connect it. Then
+  ;; evaluate some code in this Rich comment block. Or just write
+  ;; sme new code and evaluate that. Or whatever. It's fun!
```
Comment (phrohdoh) [inline assets/getting-started-content/activate.cljs:17]:
```suggestion
  ;; some new code and evaluate that. Or whatever. It's fun!
```

**Comment by PEZ** [comment]
@phrohdoh : Sorry for missing your typo fix. Please feel free to PR it. There are probably more typos in there. I'm slightly dyslectic, I think.
